name: terraform deploy
on:
  workflow_dispatch

jobs:
  deploy:
    name: 'terraform-deploy'

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: dev
    env:
      TF_VAR_env: "DEV"
      TF_VAR_snowflake_account: "${{vars.SNOWFLAKE_ACCOUNT}}"
      TF_VAR_snowflake_region: "${{vars.SNOWFLAKE_REGION}}"
      TF_VAR_snowflake_username: "${{vars.SNOWFLAKE_USERNAME}}"
      TF_VAR_snowflake_password: "${{secrets.SNOWFLAKE_PASSWORD}}"
      TF_VAR_snowflake_role: "${{vars.SNOWFLAKE_ROLE}}"

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    
    - name: terraform init
      run: terraform -chdir=./terraform/snowflake init

    - name: terraform validate
      run: terraform validate -no-color

    - name: terraform plan
      run: terraform -chdir=./terraform/snowflake plan -no-color -input=false -lock=false
      continue-on-error: false

    - name: terraform apply
      run: terraform -chdir=./terraform/snowflake apply -auto-approve -input=false
